# Generated by Django 2.2.7 on 2019-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_juego_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
    ]
