# Generated by Django 2.2.7 on 2019-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20191119_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
