# Generated by Django 2.2.7 on 2019-11-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20191119_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['plataforma'],
            },
        ),
        migrations.DeleteModel(
            name='JuegoInstance',
        ),
        migrations.AddField(
            model_name='juego',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Platform'),
        ),
    ]
